version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sqs-practice"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1wcc1rlbjeh9t"
s3_prefix = "sqs-practice"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
