AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Practicing SQS

Globals:
  Function:
    Timeout: 10
    Runtime: python3.8

Resources:
  DeadLetter:
    Type: AWS::SQS::Queue

  RawQueue:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 0
      # MessageRetentionPerion: 1209600
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetter.Arn
        maxReceiveCount: 4
      # Tags:
      #   - Key: Practice
      #   Value: SQS
      VisibilityTimeout: 120

  RawQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
       - !Ref RawQueue
      PolicyDocument:
        Id: RawQueuePolicy
        Version: '2012-10-17'
        Statement:
        - Sid: Allow-User-SendMessage
          Effect: Allow
          Action:
            - SQS:SendMessage
            - SQS:ReceiveMessage
          Resource: !GetAtt RawQueue.Arn

  TriggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/TriggerFn/
      Handler: app.lambda_handler
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt RawQueue.Arn
            BatchSize: 10
            Enabled: true
      Policies:
      - SQSPollerPolicies:
          QueueName: !Ref RawQueuePolicy

CreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/CreateFn/
      Handler: app.lambda_handler   
      Architectures:
        - x86_64
      Environment:  
      Events:
        CreateOperation:
          Type: Api
          Properties:
            Path:  /activities
            Method: post
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !Ref RawQueuePolicy

Outputs:
  RawSqsUrl:
    Description: URL of the sqs event
    Value: !Ref RawQueue
 
  DeadLetterUrl:
    Description: URL of the sqs event
    Value: !Ref DeadLetter